version: '3.3'

services:
  server:
    build: .
    # volumes:
      # - 'data:/go:rw'
      # - './prometheus.yml:/etc/prometheus:rw'
    expose:
      - 9090
    ports:
      - 9090:9090
    # command: ./prometheus -config.file=prometheus.yml
  grafana:
    build: ./grafana
    expose:
      - 3000
    ports:
      - 3000:3000
    # volumes:
    #   - grafana-storage
  client:
    build: ./client
    volumes:
      # - 'data:/go:rw'
      - './client:/go/src/client'
    links:
      - server
    expose:
      - 8080
    ports:
      - 8080:8080
    command: bash -c 'cd /go/src/client && fresh'
  client2:
    build: ./client
    volumes:
      # - 'data:/go:rw'
      - './client:/go/src/client'
    links:
      - server
    expose:
      - 8081
    ports:
      - 8081:8081
    command: bash -c 'cd /go/src/client && fresh'
volumes:
  data:
    driver: 'local'
