version: '3.3'

services:
  server:
    build: ./prometheus
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:rw'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - client
      - client2
  client:
    build: ./client
    volumes:
      - './client:/go/src/client'
    expose:
      - 8080
    ports:
      - 8080:8080
    command: bash -c 'cd /go/src/client && fresh'
  client2:
    build: ./client
    volumes:
      - './client:/go/src/client'
    expose:
      - 8080
    ports:
      - 8081:8080
    command: bash -c 'cd /go/src/client && fresh'
  grafana:
    build: ./grafana
    expose:
      - 3000
    ports:
      - 3000:3000
volumes:
  data:
    driver: 'local'
